// "use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Header from "../components/Header/Header"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sourav Mondal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  let msg = "helow, i m popup"

  let PopAnimation = () => {
    return (
      <div className=' h-screen w-screen bg-green-300' >
        <h1>{msg}</h1>
      </div>
    )
  }


  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <footer>This is Footer</footer>
      </body>
    </html>
  )
}
