"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Header from "../components/Header/Header"



import { useEffect, useState } from "react";
import Link from 'next/link';
import Image from 'next/image';
import ani3 from "../public/animation/a3.gif"
import Loader from '@/components/Loader/Loader';



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sourav Mondal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {



  const [showPage, setShowPage] = useState(false);

  function myFunction() {
    setShowPage(true)
  }

  useEffect(() => {
    setTimeout(myFunction, 1900);
  }, [])





  return (
    <html lang="en">
      <body className={inter.className}>
        {
          showPage 
          ? <>
              <Header />
              {children}
              <footer>This is Footer</footer>
            </>
          : <Loader></Loader>
        }
      </body>
    </html>
  )
}
